content/authors/crystal-steltenpohl/_index.md

There was a space and Netlify didnt build the website, so I fixed it. 
Any comments?

fixed indentation in crystal's file

---

assets/scss/custom.scss
layouts/partials/navbar.html
layouts/partials/search.html
layouts/partials/widgets/featurette_alternative.html
layouts/partials/widgets/portfolio.html
layouts/shortcodes/resources.html

Design can always change, but the mechanics is okay (I think). 
Also improved a bit UX in the navbar.

Automation of Curated resources

---

content/about/mission/advocacy.md
content/clusters/cluster1.md
content/clusters/cluster2.md
content/clusters/cluster3.md
content/clusters/cluster4.md
content/clusters/cluster5.md
content/clusters/cluster6.md
content/clusters/cluster7.md

fingers crossed I didnt break anything

sam started editing the clusters

---

content/iwiki/index.md
content/iwiki/wiki.md

The PR adds a page at /wiki displaying the remote wiki. It should already blend in well with the page template.

Add embedded wiki.

---

config/_default/menus.toml

reordering menu

---

LICENSE.md
README.md
config/_default/params.toml
layouts/partials/site_footer.html
layouts/partials/site_footer_license.html

Change license

---

config/_default/menus.toml
content/authors/bethan-iley/_index.md
content/neurodiversity/index.md
content/neurodiversity/neurodiversity.md

Also added the Team Neurodiversity page to the website menu, and updated my personal information card.
I tested this using a local Hugo server, it loaded and displayed the changes.

Added Team Neurodiversity page content

---

content/authors/julia-pauquet/_index.md

added profile to add to contributor page for the FOERRT_bot created during the Open Science Retreat 2024

added user profile for julia pauquet

---

.github/workflows/deploy.yaml

fix GHA to run hugo v0.123.3

---

config/_default/menus.toml
content/newsletters/index.md

To make past newsletters easily accessible, I've consolidated all the archives onto a single, dedicated page. Now you can quickly find the information you need!

Newsletters Archive Display Page

---

content/newsletters/index.md

April Newsletter added on the website

Added April Newsletter

---

content/educators-corner/017-teaching-os-to-undergraduates/index.md

Hi 
Hope you are doing well 
Added the content for the Open Science Course 101 by Dermott Lynott 
Would like a review 
Thanks @bethaniley @flavioazevedo @DAKiersz @Dermott-lynott

Course on Open Science 101 by Dermott Lynott

---

content/newsletters/index.md

Added May Newsletter  to the website page

Add May Newsletter

---

config/_default/menus.toml

@LukasRoeseler can you approve?

Add direct links to FReD shiny apps

---

.github/workflows/reminder_create.yml
.github/workflows/reminder_remind.yml

Ref: https://github.com/agrc/reminder-action/issues/185

Add pull request permissions for reminder action

---

content/home/4-newsletter.md
content/newsletters/index.md
layouts/shortcodes/subscribe.html

@kellyLlyod 
Here is the preview of the codes shared 
checkout the ```kellyllyod``` branch  on the Newsletters Archive Page for a preview

Kelly Llyod [Subscribe form to the Newsletter ]

---

content/teaching_os/index.md
content/teaching_os/postEdu.md

The mobile view had some small issues 
Fixed :+1: 
@flavioazevedo  you can  review this as soon as possible and merge it

Mobile View Fixes [PostEdu]

---

config/_default/menus.toml
content/impact/impact.md
content/mapping_os/index.md
content/mapping_os/mapping_os.md
content/publications/publications.md
content/replication-hub/replication-hub.md

[don't approve this yet, I just want to see it in staging format after checking it locally]

Adding Mapping OS

---

content/educators-corner/018-accessible-feedback-in-research/_index.md

[Accessible Feedback in Research ](https://staging.forrt.org/educators-corner/018-accessible-feedback-in-research/ )

Final touches as Suggested by Leticia

---

config/_default/menus.toml
content/replication-hub/_index.md
content/replication-hub/index.md
content/replication-hub/submit/_index.md
content/replication-hub/submit/submit.mdOUT
layouts/partials/navbar.html
static/apps/fred_annotator.html
static/apps/fred_explorer.html

Add iframes and app URL masking

---

content/newsletters/index.md
layouts/shortcodes/subscribe.html

Adding  October and September Newsletters  to the newsletter page Archive 
See [here](http://localhost:1313/newsletters/)

Add october and september on newsletter page Archives

---

content/about/about/newsletter.md
content/about/get-involved/newsletter.md
content/publications/newsletter.md

Newsletter subscription form at Publications and About  pages via Formspree  to Mailchimp 
issue number #192

Newsletter Form update 

---

content/newsletters/index.md

Just updated the Archive page with the November Newsletter

Add November Newsletter Link 

---

content/newsletters/index.md

Added January newsletter to the archives page
also made some small fixes

Add January Newsletter

---

.github/workflows/check_images.yaml
scripts/webp_conversion/check_images_in_pr.py

@richarddushime the picture check broke when we switched to pull_request_target - I hope this adjustment makes it find the PR number again

Try to restore pic check action (pull PR number correctly)

---

.github/workflows/check_images.yaml

Reverts forrtproject/forrtproject.github.io#239
@LukasWallrich  you can merge this  to fix it immediate

Revert "workflow update to pass PRs from Forks repos"

---

config/_default/menus.toml

There are now some equal weights - they should be arranged alphabetically, but let's check staging.

Arrange about menu alphabetically

---

content/home/10-social.md

@flavioazevedo as discussed - pls approve

Remove twitter/x integration

---

content/home/8-contact.md
layouts/partials/site_head.html
themes/academic/data/assets.toml

They are quite big now, all at the bottom of the homepage ... but still better to have than not to have

Add all social media links to homepage

---

content/newsletters/index.md

Add February 2025 Newsletter

---

config/_default/config.toml
themes/academic/assets/css/404.css
themes/academic/layouts/404.html

Customised the 404 page 
issue #244

Add note to 404 to contact us with broken links #244

---

.github/workflows/deploy.yaml

Instead of using V9 , I used the commit hash for security

Updated CI download to LTS Version 

---

.github/workflows/link-check.yaml

Given recent issues with broken links (e.g.  #244), this regularly checks for broken links on the website and notifies us in an issue (a single issue, so no spam) if any are found.
- Not Tested yet
- [x ] I have performed a self-review of my own code.
- [ NA] I have commented my code, particularly in hard-to-understand areas.

Add link check actions

---

content/coc.md

Remove defunct COC committee

---

content/mapping_os/mapping_os.md

Datasets Considered for Integration  on Mapping OS

Datasets Considered for Integration section 2  additions

---

.github/workflows/data-processing.yml
scripts/gs-cite/google_scholar.py

Correct check for SERPAPI key

---

content/lesson-plans/nd-lessons-plans.md

Display G-sheet in the lesson plans page 

---

.github/workflows/data-processing.yml
.github/workflows/deploy.yaml
scripts/contributor-analysis/contributor_analysis.rmd

Removed network graphs that aren't needed and fixed label on top 10 projects graph

Update contributor_analysis.rmd - fixing graphs

---

.github/workflows/deploy.yaml

Currently, there is no way to manually update the website data from master - e.g., when Tenzing sheets have changed. This ensures that this is possible (though still fiddly, as data processing and then deploy steps need to be run manually)

Enable prod deploy from workflow_dispatch

---

.github/workflows/data-processing.yml
scripts/gs-cite/google_scholar.py

The data processing action failed to commit the Google Scholar image - so that it was not updated successfully. This should fix that

Get Google Scholar chart to update

---

content/cv/cv.md

Update cv.md - added link to new cv pdf file

---

scripts/forrt_contribs/tenzing.py

At his request, actually at his several requests, and I'm sick of hearing about it so I've done it now and he owes me big time.

Update tenzing.py - Putting Flavio last on the contributors page

---

content/contributor-analysis/_index.md

Update _index.md - fixing contributor analysis figure names

---

scripts/forrt_contribs/tenzing.py

Apparently there was an additional issue with asterisks on FAs name in tenzings that made this tricky - should be fixed now with any luck otherwise he can bloody sort it out himself

Update tenzing.py - still trying to get FA's name last

---

scripts/forrt_contribs/tenzing.py

The changes didn't work so I'm undoing them and will come back to this later when I have more time

Update tenzing.py - undoing changes trying to put FA last

---

.github/workflows/data-processing.yml

Currently, there are errors in the data processing action, as reported by @richarddushime  - this should fix them.

Fix R package installation in data-processing.yml

---

scripts/contributor-analysis/contributor_analysis.rmd

Made the date look nicer and took out Susanne's note about the network graph

Update contributor_analysis.rmd - tidying text

---

content/replication-hub/submit/index.md

Change from socpsy to google forms

---

content/newsletters/index.md
content/replication-hub/_index.md

April Newsletter and replication reseach clickable image

 Add April Newsletter and replication reseach clickable image

---

.github/workflows/data-processing.yml
layouts/partials/page_header.html
layouts/partials/page_links_div.html
layouts/partials/site_head.html
layouts/plain_page/single.html
scripts/contributor-analysis/contributor_analysis.rmd

Currently, the beautiful Tenzing network graph does not show up - thix fixes it.
NB: Change can only be shown after the data processing has been run from this new action - so staging may not work.
My changes *may* create a new warning - though I am not sure why this would be triggered, and whether it was there before ...

Fix display of network

---

content/publications/publications.md

Following the recent comment [here ](https://github.com/forrtproject/forrtproject.github.io/pull/331#issuecomment-2869181766) I am suggesting  these improvements  [here (stagging site)](https://staging.forrt.org/publications/)

Publications  layout minor Fixes

---

content/publications/publications.md

Minor Fixes on the  publications pages and link fix

Fixes Broken link, layout on publications 

---

scripts/contributor-analysis/contributor_analysis.rmd

Added link to contributors page
Changed groups to projects on network graph label

Update contributor_analysis.rmd - refining network graph

---

scripts/forrt_contribs/tenzing.md

Update tenzing.md - including link to contributor analysis

---

scripts/contributor-analysis/contributor_analysis.rmd

Update contributor_analysis.rmd - fixing my typos!!

---

content/publications/publications.md

Fixes # Add New Pub Papers to Publications page

Add New Pub Papers to Publications page

---

content/publications/publications.md

Fixes # Add Citations politics preprint and minor updates

Add Citations politics preprint and minor updates

---

scripts/forrt_contribs/tenzing.py

Add some logging for tenzing generation to support troubleshooting
Can only be tested as GH action when on branch

Logging for tenzing.py

---

.gitignore
content/publications/publications.md

Fixes # publications: contents update

publications: contents update

---

.gitignore
content/publications/1-hero.md
content/publications/newsletter.md
content/publications/publications.md

Cleaning unecessary comments [publicataions folder]

---

content/publications/publications.md

Fixes 
Add new preprint [In Pursuit of Citational Justice: A Toolkit for Equitable Scholarship]
_still missing a DOI_

Add new preprint [In Pursuit of Citational Justice: A Toolkit for Equitable Scholarship]

---

content/citation-politics/_index.md
content/citation-politics/toolkit/index.md
content/publications/publications.md

updates new doi to [ In Pursuit of Citational Justice preprint ]

updates new doi to [ In Pursuit of Citational Justice preprint ]

---

content/mapping_os/mapping_os.md
static/apps/os_map.html

This adds a link to the new open science map.

Add os map

---

.github/workflows/deploy.yaml
.github/workflows/staging-aggregate.yaml

Fixes #309  (issue)
- New staging-aggregate.yaml workflow for combining multiple PRs
- Triggers on any PR event targeting master branch
- Skips conflicting PRs and continues with others
- Includes all open PRs regardless of CI status
- Deploys to staging.forrt.org via external repository
- Manual trigger option for force deployment

Add aggregated staging deployment workflow

---

.github/workflows/data-processing.yml

Bug fix in data processing , i forgot to update the branch while checking out master and i was using  ga (old branch i used to test)

Fix: Change data-processing workflow to use master branch

---

data/ga_data.json

Update GA data - 2025-08-28 20:25:43 UTC

---

content/imprint/index.md
layouts/partials/site_footer.html

Need to check in staging whether this shows up in the footer - if so, would be good to add, mostly to clarify that this is *not* the Verein's page

Add imprint

---

layouts/shortcodes/subscribe.html

Reverts forrtproject/forrtproject.github.io#431

Revert "[Draft]Newsletter Updates"

---

data/ga_data.json

Automated monthly Google Analytics data update. Generated on 2025-09-14 14:42:24 UTC. Files changed: data/ga_data.json

📊 Monthly GA Data Update - September 2025
